### ISSUE TITLE
Bug: Lighting logs on floors (second click item)

### ISSUE THREAD

**Issue by syuil** [RSPSApp/elvarg-rsps#183]
java.lang.IndexOutOfBoundsException
	at io.netty.buffer.EmptyByteBuf.readShort(EmptyByteBuf.java:533)

	at com.elvarg.net.packet.Packet.readShort(Packet.java:201)
[         return buffer.readShort(); ]

	at com.elvarg.net.packet.impl.SecondGroundItemOptionPacketListener.execute(SecondGroundItemOptionPacketListener.java:28)
[       final int itemId = packet.readShort(); ]

	at com.elvarg.net.PlayerSession.processPackets(PlayerSession.java:142)
	at com.elvarg.game.entity.impl.player.Player.process(Player.java:391)
	at com.elvarg.game.World$1.execute(World.java:150)
	at com.elvarg.game.entity.updating.sync.GameSyncExecutor.sync(GameSyncExecutor.java:55)
	at com.elvarg.game.World.process(World.java:145)
	at com.elvarg.game.GameEngine.run(GameEngine.java:34)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)

**Comment by DrHenny** [comment]
What branch is this? master?

**Comment by syuil** [comment]
> What branch is this? master?

Yeah, I was lighting Yew Logs on the floor. I was also in 50+ wilderness (yew tree near the wilderness web) if that helps with anything

**Comment by DrHenny** [comment]
fixed
